name: snapchef

description: A mobile app for creating AI-generated recipes based on available ingredients.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:      
    sdk: flutter    
  flutter_dotenv: ^5.2.1
  flutter_localizations: 
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_speed_dial: ^7.0.0
  flutter_tts: ^4.2.2
  provider: ^6.0.0
  image_picker: ^0.8.5+3
  http: ^1.3.0
  http_parser: ^4.0.0
  shared_preferences: ^2.5.3
  mime: ^1.0.6
  firebase_messaging: ^14.6.6  
  firebase_core: ^2.32.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true  
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  