name: snapchef

description: A mobile app for creating AI-generated recipes based on available ingredients.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:      
    sdk: flutter    
  flutter_dotenv: ^5.2.1
  flutter_localizations: 
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_markdown: ^0.7.7
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flutter_timezone: ^4.1.0
  flutter_tts: ^4.2.2
  http: ^1.3.0
  http_parser: ^4.0.0  
  image_picker: ^1.1.2
  intl: 0.20.2
  mime: ^2.0.0
  provider: ^6.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.0    
  firebase_messaging: ^15.2.5  
  firebase_core: ^3.13.0 
  google_mlkit_barcode_scanning: ^0.14.1 
  google_sign_in: ^6.3.0  
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  web_socket_channel: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
  
  fonts:
    - family: BerlinSansFBDemi
      fonts:
        - asset: assets/fonts/BerlinSansFBDemiBold.ttf

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true  
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#f47851"
  image: assets/images/splash_icon.png  
  android: true
  android_12:
    color: "#f47851"
    image: assets/images/splash_icon.png
    icon_background_color: "#F47851"
  android_gravity: center
  ios: true
  web: false
        